name: Run go test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-go-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: go test ./...
